name: Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build_debug:
    runs-on: ubuntu-latest
    container: gitlab-registry.cern.ch/acts/machines/ubuntu2004:master
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: >
          cmake -B build -S .
          -GNinja
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_FLAGS=-Werror
          -DACTS_BUILD_DD4HEP_PLUGIN=off
          -DACTS_BUILD_DIGITIZATION_PLUGIN=on
          -DACTS_BUILD_IDENTIFICATION_PLUGIN=on
          -DACTS_BUILD_JSON_PLUGIN=on
          -DACTS_BUILD_TGEO_PLUGIN=on
          -DACTS_BUILD_LEGACY=on
          -DACTS_BUILD_FATRAS=on
          -DACTS_BUILD_BENCHMARKS=on
          -DACTS_BUILD_UNITTESTS=on
      - name: Build
        run: cmake --build build --
      - name: Unit tests
        run: cmake --build build -- test
      - name: Remove .o files
        run: >
          du -sh build
          && find build -name *.o -delete
          && du -sh build
      - name: Coverage
        run: >
          pip3 install gcovr
          && cd build
          && /usr/bin/python3 ../CI/test_coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/coverage/cov.xml
